name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: self-hosted
    container:
      image: timbru31/node-alpine-git:14
      options: --rm -v /opt/secrets:/opt/secrets
      env:
        NPMRC: ${{ secrets.NPMRC }}      
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: |
          #!/bin/bash
          set -e
          git config --global user.email "chang@nextbillion.ai"
          git config --global user.name "chang"
          git config --global --add safe.directory /__w/k10s/k10s
          cat $NPMRC > ~/.npmrc
          yarn
          yarn publish --new-version ${GITHUB_REF#refs/tags/}
